### PR TITLE
⚠️ CONFLICT! Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request: CONFLICT #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-ansible-role.git`](https://github.com/cisagov/skeleton-ansible-role.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/ansible-role-pca-gophish-composition.git ansible-role-pca-gophish-composition
    cd ansible-role-pca-gophish-composition
    git remote add skeleton https://github.com/cisagov/skeleton-ansible-role.git
    git remote set-url --push skeleton no_push
    git switch develop
    git switch --create lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add .github/dependabot.yml molecule/default/molecule.yml molecule/default/molecule.yml~c121f6c2d751ea234695e5ff5188c9a834537efd 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may *append* to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Confirm each item in the "Pre-approval checklist" below.

1. Remove any of the checklist items that do not apply.

1. Ensure every remaining checkbox has been checked.

1. Mark this draft pull request "Ready for review".

## ✅ Pre-approval checklist ##

Remove any of the following that do not apply. If you're unsure about
any of these, don't hesitate to ask. We're here to help!

- [x] ✌️ The conflicts in this pull request have been resolved.
- [x] All relevant type-of-change labels have been added.
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Revert dependencies to default branches.

---

> [!NOTE]
> You are seeing this because one of this repository's maintainers has
> configured [Lineage] to open pull requests.

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by jsf9k** [comment]
@mcdonnnj - I'd like to know what you think about commit fa68571.  I had to make that change in order to get tests to pass, but (1) I'm not certain I tracked down exactly why it is necessary and (2) maybe there is a better way to work around it.

**Comment by dav3r** [comment]
> @mcdonnnj - I'd like to know what you think about commit [fa68571](https://github.com/cisagov/ansible-role-pca-gophish-composition/commit/fa6857168d56a8fb35782f1e68c49fde04a816fa). I had to make that change in order to get tests to pass, but (1) I'm not certain I tracked down exactly why it is necessary and (2) maybe there is a better way to work around it.

Not sure if I've thought this through, but if we changed the package name from [`gophish_init`](https://github.com/cisagov/pca-gophish-composition/blob/2aef50039b351e2ff44a47dad558294c8856019c/setup.py#L45) to `gophish-init`, would that help us out here?

**Comment by mcdonnnj** [comment]
> > @mcdonnnj - I'd like to know what you think about commit [fa68571](https://github.com/cisagov/ansible-role-pca-gophish-composition/commit/fa6857168d56a8fb35782f1e68c49fde04a816fa). I had to make that change in order to get tests to pass, but (1) I'm not certain I tracked down exactly why it is necessary and (2) maybe there is a better way to work around it.
> 
> Not sure if I've thought this through, but if we changed the package name from [`gophish_init`](https://github.com/cisagov/pca-gophish-composition/blob/2aef50039b351e2ff44a47dad558294c8856019c/setup.py#L45) to `gophish-init`, would that help us out here?

I think we should do that because I think that would make the expected result clear.

Also @jsf9k regarding [5c904c9](https://github.com/cisagov/ansible-role-pca-gophish-composition/pull/52/commits/5c904c9df7ada8ed983dd74c5d222a93849eab1c) as of https://github.com/cisagov/ansible-role-docker/pull/70 AL2023 should be supported as long as Docker is the only blocker. I've been planning on going back and updating other roles that have disabled it for the same reason to enable AL2023 support and make sure everything works as expected.

**Comment by jsf9k** [comment]
> Also @jsf9k regarding [5c904c9](https://github.com/cisagov/ansible-role-pca-gophish-composition/pull/52/commits/5c904c9df7ada8ed983dd74c5d222a93849eab1c) as of [cisagov/ansible-role-docker#70](https://github.com/cisagov/ansible-role-docker/pull/70) AL2023 should be supported as long as Docker is the only blocker. I've been planning on going back and updating other roles that have disabled it for the same reason to enable AL2023 support and make sure everything works as expected.

Please see commit 204ce11.

**Review by dav3r — APPROVED** [review]
👍

**Comment by jsf9k** [comment]
> > Not sure if I've thought this through, but if we changed the package name from [`gophish_init`](https://github.com/cisagov/pca-gophish-composition/blob/2aef50039b351e2ff44a47dad558294c8856019c/setup.py#L45) to `gophish-init`, would that help us out here?
> 
> I think we should do that because I think that would make the expected result clear.

@dav3r and @mcdonnnj - Please see cisagov/pca-gophish-composition#57 as well as commits 44209b5 and 2c3a2d6 of this pull request.

**Review by dav3r — APPROVED** [review]

**Review by dv4harr10 — APPROVED** [review]

**Comment by jsf9k** [comment]
> Also @jsf9k regarding [5c904c9](https://github.com/cisagov/ansible-role-pca-gophish-composition/pull/52/commits/5c904c9df7ada8ed983dd74c5d222a93849eab1c) as of [cisagov/ansible-role-docker#70](https://github.com/cisagov/ansible-role-docker/pull/70) AL2023 should be supported as long as Docker is the only blocker. I've been planning on going back and updating other roles that have disabled it for the same reason to enable AL2023 support and make sure everything works as expected.

@mcdonnnj - I went ahead and revisited the other roles and created PRs.  Please check to see if there are any that I missed.

**Comment by jsf9k** [comment]
See also [@mcdonnnj's final comment](https://github.com/cisagov/pca-gophish-composition/pull/57#pullrequestreview-2012138239) in cisagov/pca-gophish-composition#57.

**Pull request merged**
